<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Description>WIP - A simple sdk to write easy and fast tests for your web api's</Description>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/_git/AspNetCore.Simple.MsTest.Sdk</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/_git/AspNetCore.Simple.MsTest.Sdk</RepositoryUrl>
        <PackageTags>C#;.NetCore;Asp.NetCore;NetCore;ASPNetCore;Test;MsTest;</PackageTags>
        <PackageReleaseNotes>WIP - A simple sdk to write easy and fast tests for your web api's</PackageReleaseNotes>
        <ApplicationIcon />
        <OutputType>Library</OutputType>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <AssemblyName>AspNetCore.Simple.MsTest.Sdk</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GitVersion.MsBuild" Version="5.6.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>
