<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Descriptiotn>A simple sdk to write easy and fast tests for your web api's</Descriptiotn>
        <Copyright>Copyright 2021 (c) Rene Peuser. All rights reserved.</Copyright>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/_git/AspNetCore.Simple.MsTest.Sdk</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/_git/AspNetCore.Simple.MsTest.Sdk</RepositoryUrl>
        <PackageTags>C#;.NetCore;Asp.NetCore;NetCore;ASPNetCore;Test;MsTest;</PackageTags>
        <PackageReleaseNotes>Fix bugs with error output if call went wrong, like not found, method not allowed etc.</PackageReleaseNotes>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <ApplicationIcon />
        <StartupObject />
        <PackageId>AspNetCore.Simple.MsTest.Sdk</PackageId>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
    </PropertyGroup>

    <!--Property group settings for source link !-->
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="..\..\readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile>.\AspNetCore.Simple.MsTest.Sdk.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Extensions.Pack" Version="6.0.6" />
        <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.8" />
        <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="8.0.0" PrivateAssets="All" />
        <PackageReference Include="MSTest.TestFramework" Version="3.10.2" />
        <PackageReference Include="ConsoleTables" Version="2.6.2" />
        <PackageReference Include="System.CodeDom" Version="9.0.8" />
    </ItemGroup>

</Project>
