<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Payloads\NewPerson.json" />
        <None Remove="Payloads\NewPersonParameter.json" />
        <None Remove="Payloads\SonGoku.json" />
        <None Remove="Results\ErrorResponse.json" />
        <None Remove="Results\GetPersonResponse.json" />
        <None Remove="Results\NewPerson.json" />
        <None Remove="Results\SonGoku.json" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Payloads\NewPersonParameter.json" />
        <EmbeddedResource Include="Payloads\NewPerson.json" />
        <EmbeddedResource Include="Payloads\InvalidSonGoku.json" />
        <EmbeddedResource Include="Payloads\SonGoku.json" />
        <EmbeddedResource Include="Results\NewPersonParameter.json" />
        <EmbeddedResource Include="Results\SonGokuNewResponse.json" />
        <EmbeddedResource Include="Results\SonGoku.json" />
        <EmbeddedResource Include="Results\ErrorResponse.json" />
        <EmbeddedResource Include="Results\GetPersonResponse.json" />
        <EmbeddedResource Include="Results\NewPerson.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="9.0.1" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.7.2" />
        <PackageReference Include="MSTest.TestFramework" Version="3.7.2" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk.Api\AspNetCore.Simple.MsTest.Sdk.Api.csproj" />
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk\AspNetCore.Simple.MsTest.Sdk.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.test.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>