<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Results\ErrorResponse.json" />
      <None Remove="Results\GetPersonResponse.json" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Results\ErrorResponse.json" />
      <EmbeddedResource Include="Results\GetPersonResponse.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.6" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
        <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk.Api\AspNetCore.Simple.MsTest.Sdk.Api.csproj" />
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk\AspNetCore.Simple.MsTest.Sdk.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.test.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
