<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <NoWarn>CA1515;CA1707;CA1054;CA1062;MSTEST0016</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Controllers\Requests\NewPerson.json" />
        <None Remove="Controllers\Requests\NewPersonParameter.json" />
        <None Remove="Controllers\Requests\SonGoku.json" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="AnyFolder\P\NewPersonParameter.json" />
        <EmbeddedResource Include="AnyFolder\R\NewPersonParameter.json" />
        <EmbeddedResource Include="Controllers\Requests\NewPersonParameter.json" />
        <EmbeddedResource Include="Controllers\Requests\NewPerson.json" />
        <EmbeddedResource Include="Controllers\Requests\InvalidSonGoku.json" />
        <EmbeddedResource Include="Controllers\Requests\SonGoku.json" />
        <EmbeddedResource Include="Controllers\Responses\NewPersonParameter.json" />
        <EmbeddedResource Include="Controllers\Responses\InvalidSonGoku.json" />
        <EmbeddedResource Include="Controllers\Responses\SonGokuNewResponse.json" />
        <EmbeddedResource Include="Controllers\Responses\SonGoku.json" />
        <EmbeddedResource Include="Controllers\Responses\ErrorResponse.json" />
        <EmbeddedResource Include="Controllers\Responses\GetPersonResponse.json" />
        <EmbeddedResource Include="Controllers\Responses\NewPerson.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.0.2" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk.Api\AspNetCore.Simple.MsTest.Sdk.Api.csproj" />
        <ProjectReference Include="..\AspNetCore.Simple.MsTest.Sdk\AspNetCore.Simple.MsTest.Sdk.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.test.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>